/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_6 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alusignal,
    output reg [15:0] s,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] holder;
  
  always @* begin
    if (alusignal[0+0-:1]) begin
      holder = a + b;
    end else begin
      holder = a - b;
    end
    s = holder;
    z = ~(|holder);
    v = ((alusignal[0+0-:1] ^ a[15+0-:1]) & (alusignal[0+0-:1] ^ b[15+0-:1]) ^ !holder[15+0-:1]) | (!(alusignal[0+0-:1] ^ a[15+0-:1]) & !(alusignal[0+0-:1] ^ b[15+0-:1]) & (holder[15+0-:1]));
    n = holder[15+0-:1];
  end
endmodule
